### ISSUE TITLE
Main game loop

### ISSUE THREAD

**Issue by majate** [Gustavrohss/EverythingIsWrong#14]
There are some things that needs to be implemented in the game loop.

- [x] Only the host should be able to start a new game round. Right now, any player can choose to start the game in the lobby, or go to the next question.

- [x] There should be a fixed amount of questions, and you should only be able to go to the results view when the game is over.

**Comment by Gustavrohss** [comment]
The final details for fixed number of questions remains.

**Comment by Gustavrohss** [comment]
Lives on in #35.
