### ISSUE TITLE
API status feedback

### ISSUE THREAD

**Issue by majate** [Gustavrohss/EverythingIsWrong#18]
Users should get feedback when the application is fetching data or API/backend related errors occurs (e.g. connection error, Clarifai request limits or other errors).

**Comment by Truchisushi** [comment]
Got a simple feedback for loading screen. A big issue I found is that many of the promises are returned almost directly from firebase, while firebase does a lot of the bulk job (doing the calls to clarifai and imgur). This required me to add "isLoading" into the gameInfo and a listener to it to display loading screen :slightly_smiling_face: I made a loader container too which can be added with a spinner or whatever we like

**Comment by Truchisushi** [comment]
What more possible feedback do we want from firebase and such?

**Comment by Gustavrohss** [comment]
This issue is dependent on lots of different further development. Keeping it open until shortly before final deployment.
