### ISSUE TITLE
Persisted state

### ISSUE THREAD

**Issue by majate** [Gustavrohss/EverythingIsWrong#34]
From grading criteria:
Application state persisted at server, for each user.

> Ask Abdul what is needed. Do we need high scores or cookies? Should we instead start implementing user accounts?

**Comment by Gustavrohss** [comment]
Taking a look at this.

Going to try to implement some simple hash(username + password) system to save favorite game rounds.

**Comment by Gustavrohss** [comment]
High scores are implemented through a rudimentary login system. May or may not implement the option to log in at the results screen, if not yet logged in.
