### ISSUE TITLE
Check that the image exists 

### ISSUE THREAD

**Issue by majate** [Gustavrohss/EverythingIsWrong#37]
If it’s possible, try to check that the image from imgur is a valid image. We don’t want this to happen:
![E48030C7-2CBF-4416-88CC-CF800E0A8EC7](https://user-images.githubusercontent.com/34208794/79683199-9b0f5f00-8228-11ea-9ef3-f46f15ce667b.png)

**Comment by Gustavrohss** [comment]
This is a bug in the API, seemingly.
There isn't anything we have been able to do to fix this.
